platform: linux/amd64

pipeline:
  build:
    image: docker:dind
    environment:
      USER:
        from_secret:
          QUAY_USER
      TOKEN:
        from_secret:
          QUAY_TOKEN
    pull: always
    commands:
      - docker login -p $TOKEN -u $USER quay.io
      - apk add --no-cache python3 py-yaml git
      - modified=$(git diff --name-only HEAD~1..HEAD . | xargs echo)
      - echo $modified
      - ./build.py quay.io $modified
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event:
        - push
      branch:
        - master
